api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ListAuto.as_view()),
    path('<int:pk>/', views.DetailAuto.as_view()),
]

concesionaria/urls.py
from django.urls import path, include
from . import views

app_name="concesionaria"

urlpatterns = [
    path('', views.autos_render, name='autos_render'),
    #path('car/<int:car_id>', views.car_render, name='car_render_url'),
    path('car_render_url/<int:car_id>', views.car_render, name="car_render_url"),
    path('car_form', views.car_form, name='car_form_url'),
    path('guardar_auto', views.guardar_auto, name='save_car_url'),
    path('api-auth/', include('rest_framework.urls')),
]

monier_tomas/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin


#urlpatterns = [
#    url(r'^admin/', admin.site.urls),
#    url(r'^$', autos_render),
#    url(r'^car/(?P<car_id>[\w-]+)', car_render, name='view-car')
#]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('concesionaria.urls', 'concesionaria'), namespace='concesionaria')),
    path('api/v1/', include('api.urls')),
]

api/models.py
from django.db import models

# Create your models here.

concesionaria/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Auto(models.Model):
    car_model = models.CharField(max_length=20, verbose_name='Modelo')

    BRANDS = {
        ('Ford', 'FORD'),
        ('Chevrolet', 'CHEVROLET'),
    }

    car_brand = models.CharField(max_length=20, choices=BRANDS, verbose_name='Marca')

    year = models.CharField(max_length=4, verbose_name='Año')

    STATES = {
        ('Nuevo', 'NUEVO'),
        ('Usado', 'USADO'),
    }

    car_state = models.CharField(null=True, max_length=10, choices=STATES, verbose_name='Estado')

    #year_abr = year[-2:]

    def __str__(self):
        return "{} {} '{} - {}".format(self.car_brand, self.car_model, self.year_abr, self.car_state)

    class Meta:
        verbose_name = 'Auto'
        verbose_name_plural = 'Autos'


class Transaccion(models.Model):
    car = models.ForeignKey('Auto', on_delete=models.CASCADE, verbose_name='Auto', related_name='cant_transactions')

    date = models.DateField(auto_now=False, null=True, blank=False, verbose_name='Fecha')

    price = models.IntegerField(null=True, blank=False, verbose_name='Precio')

    TRANSACTION = {
        ('Compra', 'COMPRA'),
        ('Venta', 'VENTA'),
        ('Reparacion', 'REPARACION')
    }

    transaction = models.CharField(max_length=20, choices=TRANSACTION, verbose_name='Tipo de Transaccion')

    def __str__(self):
        return '{} {}'.format(self.transaction, self.car)

    class Meta:
        verbose_name = 'Transaccion'
        verbose_name_plural = 'Transacciones'

api/views.py
from django.shortcuts import render

from rest_framework import generics
from concesionaria import models
from . import serializers

# Create your views here.

class ListAuto(generics.ListCreateAPIView):
    queryset = models.Auto.objects.all()
    serializer_class = serializers.AutoSerializer

class DetailAuto(generics.RetrieveUpdateDestroyAPIView):
    queryset = models.Auto.objects.all()
    serializer_class = serializers.AutoSerializer

concesionaria/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, render_to_response
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from concesionaria.models import Auto, Transaccion

# Create your views here.

def autos_render(request):
    context = {}
    context['autos'] = Auto.objects.all()
    return render(request, 'index.html', context)

#def car_render(request, id_car):
#    car_info = {}
#    id_car_int = int(id_car)
#    car_info['car'] = Auto.objects.get(id=id_car_int)
#    print car_info
#    return render(request, 'car.html', car_info)

def car_render(request, car_id):
    context = {}
    context['car'] = Auto.objects.get(id=car_id)
    return render(request, 'car.html', context)

def car_form(request):
    context = {}
    context['brands'] = Auto.BRANDS
    context['states'] = Auto.STATES
    return render(request, 'car_form.html', context)

def guardar_auto(request):
    if request.POST:
        model = request.POST.get('model', None)
        brand = request.POST.get('brand', None)
        state = request.POST.get('state', None)
        year = request.POST.get('year', None)
        payed_price = request.POST.get('payed_price', None)
        adq_date = request.POST.get('adq_date', None)
        buy_price = request.POST.get('buy_price', None)
        if model:
            newCar = Auto()
            newCar.car_model = model
            newCar.car_brand = brand
            newCar.car_state = state
            newCar.year = year
            newCar.save()

            transBuy = Transaccion()
            transBuy.car = newCar
            transBuy.date = adq_date
            transBuy.price = payed_price
            transBuy.save()

            transSell = Transaccion()
            transSell.car = newCar
            transSell.price = buy_price
        return redirect('/')

concesionaria/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/css/materialize.min.css">

        <!-- Compiled and minified JavaScript -->
    <script
        src="https://code.jquery.com/jquery-2.2.4.min.js"
        integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
        crossorigin="anonymous">
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>

</head>

<body>

    <nav>
        <div class="nav-wrapper">
            <a href="/" class="brand-logo center">Concesionaria</a>
            <a href="/car_form" class="brand-logo right">Registrar Auto</a>
        </div>
    </nav>

    {% block index %}{% endblock %}

    {% block car %}{% endblock %}

    {% block car_registration %}{% endblock %}

    <script>
        $(document).ready(function(){
            $('select').formSelect();
        });
    </script>

</body>

</html>

concesionaria/templates/car.html
{% extends 'base.html' %}

{% block car %}
    <div class="container">
            <div class="row">
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">{{ car }}</span>
                        <p>Anio: {{ car.year }}</p>
                    </div>
                </div>
            </div>
    </div>
{% endblock %}

concesionaria/templates/car_form.html
{% extends "base.html" %}

{% block car_registration %}
    <div class="container">
        <form action="guardar_auto" method="post" target="_self">
            {% csrf_token %}

            <div class="input-field col s6">
                <select name="brand">
                    {% for brand in brands %}
                        <option value="{{ brand.0 }}">{{ brand.0 }}</option>
                    {% endfor %}
                </select>
                <label>Marca</label>
            </div>
            <br><br><br>
            Modelo:<br>
            <input name="model" type="text"><br>

            <div class="input-field col s6">
                <select name="state">
                    {% for state in states %}
                        <option value="{{ state.0 }}">{{ state.0 }}</option>
                    {% endfor %}
                </select>
                <label>Estado</label>
            </div>

            Anio:<br>
            <input name="year" type="text"><br>

            <!-- Falta hacer de que si el select es Usado tenga Reparaciones, si es Nuevo no -->
            {% if state == 'Usado' %}

            {% endif %}

            <h3>Transacciones</h3><br>

            <h4>Compra</h4><br>

            Precio:<br>
            <input name="payed_price" type="number"><br>

            Fecha:<br>
            <input name="adq_date" type="date" max=(new Date().toLocalDateString())>

            <h4>Reparaciones</h4><br>

            <!-- Falta hacer que se puedan agregar mas reparaciones -->

            Precio:<br>
            <input name="repair_price" type="number"><br>

            Fecha:<br>
            <input name="repair_date" type="date" max=(new Date().toLocalDateString())>

            <h4>Venta</h4><br>

            Precio:<br>
            <input name="buy_price" type="number"><br>

            <input type="submit" value="Subir Auto">

        </form>
    </div>

{% endblock %}

concesionaria/templates/index.html
{% extends "base.html" %}

{% block index %}
    <div class="container">
            {% for car in autos %}
                <div class="row">
                    <div class="card">
                        <div class="card-content">
                            <a href="{% url "concesionaria:car_render_url" car.id %}"><span class="card-title">{{ car }}</span></a>
                            <p>Anio: {{ car.year }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
    </div>
{% endblock %}

concesionaria/templates/template.html
<!DOCTYPE html>
<html>

<head>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/css/materialize.min.css">

        <!-- Compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/js/materialize.min.js"></script>

</head>

<body>

  <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo center" href="">Concesionaria</a>
    </div>
  </nav>
    <div class="container">
        {% for car in autos %}
            <div class="row">
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">{{ car }}</span>
                        <p>Anio: {{ car.year }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

</body>

</html>